// Code generated by mockery v2.42.2. DO NOT EDIT.

package repositories

import (
	context "context"

	entities "github.com/fmiskovic/new-amz/internal/core/entities"
	mock "github.com/stretchr/testify/mock"
)

// AccountRepositoryMock is an autogenerated mock type for the AccountRepository type
type AccountRepositoryMock[ID interface{}] struct {
	mock.Mock
}

type AccountRepositoryMock_Expecter[ID interface{}] struct {
	mock *mock.Mock
}

func (_m *AccountRepositoryMock[ID]) EXPECT() *AccountRepositoryMock_Expecter[ID] {
	return &AccountRepositoryMock_Expecter[ID]{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, account
func (_m *AccountRepositoryMock[ID]) Create(ctx context.Context, account *entities.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AccountRepositoryMock_Create_Call[ID interface{}] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account *entities.Account
func (_e *AccountRepositoryMock_Expecter[ID]) Create(ctx interface{}, account interface{}) *AccountRepositoryMock_Create_Call[ID] {
	return &AccountRepositoryMock_Create_Call[ID]{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *AccountRepositoryMock_Create_Call[ID]) Run(run func(ctx context.Context, account *entities.Account)) *AccountRepositoryMock_Create_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Account))
	})
	return _c
}

func (_c *AccountRepositoryMock_Create_Call[ID]) Return(_a0 error) *AccountRepositoryMock_Create_Call[ID] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountRepositoryMock_Create_Call[ID]) RunAndReturn(run func(context.Context, *entities.Account) error) *AccountRepositoryMock_Create_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function with given fields: ctx, id
func (_m *AccountRepositoryMock[ID]) DeleteById(ctx context.Context, id ID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountRepositoryMock_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type AccountRepositoryMock_DeleteById_Call[ID interface{}] struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - id ID
func (_e *AccountRepositoryMock_Expecter[ID]) DeleteById(ctx interface{}, id interface{}) *AccountRepositoryMock_DeleteById_Call[ID] {
	return &AccountRepositoryMock_DeleteById_Call[ID]{Call: _e.mock.On("DeleteById", ctx, id)}
}

func (_c *AccountRepositoryMock_DeleteById_Call[ID]) Run(run func(ctx context.Context, id ID)) *AccountRepositoryMock_DeleteById_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ID))
	})
	return _c
}

func (_c *AccountRepositoryMock_DeleteById_Call[ID]) Return(_a0 error) *AccountRepositoryMock_DeleteById_Call[ID] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountRepositoryMock_DeleteById_Call[ID]) RunAndReturn(run func(context.Context, ID) error) *AccountRepositoryMock_DeleteById_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *AccountRepositoryMock[ID]) GetByEmail(ctx context.Context, email string) (entities.Account, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Account, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Account); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(entities.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepositoryMock_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type AccountRepositoryMock_GetByEmail_Call[ID interface{}] struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AccountRepositoryMock_Expecter[ID]) GetByEmail(ctx interface{}, email interface{}) *AccountRepositoryMock_GetByEmail_Call[ID] {
	return &AccountRepositoryMock_GetByEmail_Call[ID]{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *AccountRepositoryMock_GetByEmail_Call[ID]) Run(run func(ctx context.Context, email string)) *AccountRepositoryMock_GetByEmail_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountRepositoryMock_GetByEmail_Call[ID]) Return(_a0 entities.Account, _a1 error) *AccountRepositoryMock_GetByEmail_Call[ID] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepositoryMock_GetByEmail_Call[ID]) RunAndReturn(run func(context.Context, string) (entities.Account, error)) *AccountRepositoryMock_GetByEmail_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: ctx, id
func (_m *AccountRepositoryMock[ID]) GetById(ctx context.Context, id ID) (entities.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ID) (entities.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ID) entities.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepositoryMock_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type AccountRepositoryMock_GetById_Call[ID interface{}] struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id ID
func (_e *AccountRepositoryMock_Expecter[ID]) GetById(ctx interface{}, id interface{}) *AccountRepositoryMock_GetById_Call[ID] {
	return &AccountRepositoryMock_GetById_Call[ID]{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *AccountRepositoryMock_GetById_Call[ID]) Run(run func(ctx context.Context, id ID)) *AccountRepositoryMock_GetById_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ID))
	})
	return _c
}

func (_c *AccountRepositoryMock_GetById_Call[ID]) Return(_a0 entities.Account, _a1 error) *AccountRepositoryMock_GetById_Call[ID] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepositoryMock_GetById_Call[ID]) RunAndReturn(run func(context.Context, ID) (entities.Account, error)) *AccountRepositoryMock_GetById_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// GetPage provides a mock function with given fields: ctx, p
func (_m *AccountRepositoryMock[ID]) GetPage(ctx context.Context, p entities.Pageable) (entities.Page[entities.Account], error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 entities.Page[entities.Account]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Pageable) (entities.Page[entities.Account], error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Pageable) entities.Page[entities.Account]); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(entities.Page[entities.Account])
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Pageable) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepositoryMock_GetPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPage'
type AccountRepositoryMock_GetPage_Call[ID interface{}] struct {
	*mock.Call
}

// GetPage is a helper method to define mock.On call
//   - ctx context.Context
//   - p entities.Pageable
func (_e *AccountRepositoryMock_Expecter[ID]) GetPage(ctx interface{}, p interface{}) *AccountRepositoryMock_GetPage_Call[ID] {
	return &AccountRepositoryMock_GetPage_Call[ID]{Call: _e.mock.On("GetPage", ctx, p)}
}

func (_c *AccountRepositoryMock_GetPage_Call[ID]) Run(run func(ctx context.Context, p entities.Pageable)) *AccountRepositoryMock_GetPage_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Pageable))
	})
	return _c
}

func (_c *AccountRepositoryMock_GetPage_Call[ID]) Return(_a0 entities.Page[entities.Account], _a1 error) *AccountRepositoryMock_GetPage_Call[ID] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepositoryMock_GetPage_Call[ID]) RunAndReturn(run func(context.Context, entities.Pageable) (entities.Page[entities.Account], error)) *AccountRepositoryMock_GetPage_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, account
func (_m *AccountRepositoryMock[ID]) Update(ctx context.Context, account *entities.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AccountRepositoryMock_Update_Call[ID interface{}] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - account *entities.Account
func (_e *AccountRepositoryMock_Expecter[ID]) Update(ctx interface{}, account interface{}) *AccountRepositoryMock_Update_Call[ID] {
	return &AccountRepositoryMock_Update_Call[ID]{Call: _e.mock.On("Update", ctx, account)}
}

func (_c *AccountRepositoryMock_Update_Call[ID]) Run(run func(ctx context.Context, account *entities.Account)) *AccountRepositoryMock_Update_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Account))
	})
	return _c
}

func (_c *AccountRepositoryMock_Update_Call[ID]) Return(_a0 error) *AccountRepositoryMock_Update_Call[ID] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountRepositoryMock_Update_Call[ID]) RunAndReturn(run func(context.Context, *entities.Account) error) *AccountRepositoryMock_Update_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// NewAccountRepositoryMock creates a new instance of AccountRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepositoryMock[ID interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepositoryMock[ID] {
	mock := &AccountRepositoryMock[ID]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
