// Package v1 Code generated by swaggo/swag. DO NOT EDIT
package v1

import (
	"github.com/swaggo/swag"
	"log"
	"os"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/v1/api",
	Schemes:          []string{"http"},
	Title:            "Book Store API",
	Description:      "Simple API to demonstrate how to write online Book Store.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

type Doc struct{}

func (s *Doc) ReadDoc() string {
	content, err := os.ReadFile("./docs/v1/swagger.json")
	if err != nil {
		log.Fatalf("Failed to read json file: %v", err)
	}
	return string(content)
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), &Doc{})
}
